name: Build ZamFit Pro APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release --target-platform android-arm64 --split-per-abi
      - uses: actions/upload-artifact@v4
        with:
          name: ZamFit-Pro-APK
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
